# Copyright (C) 2023 Edge Network Technologies Limited
# Use of this source code is governed by a GNU GPL-style license
# that can be found in the LICENSE.md file. All rights reserved.

version: "3"

volumes:
  apps:
  data:

services:
  arangodb:
    image: arangodb:latest
    env_file: .env
    volumes:
      - apps:/var/lib/arangodb3-apps
      - data:/var/lib/arangodb3
    ports:
      - "8529:8529"

  lottery:
    build: .
    image: lottery:latest
    env_file: .env
    ports:
      - "8777:8777"
